[package]
name = "agent_conversation"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
rig-core = "0.18.2"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
